<?php
/**
 * This page displays the student ranks generated by /mod/studentquiz.
 *
 * @package    mod_studentquiz
 * @copyright  2017 HSR (http://www.hsr.ch)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

require_once(dirname(dirname(__DIR__)).'/config.php');
require_once(__DIR__.'/reportlib.php');
require_once(__DIR__.'/classes/event/studentquiz_report_rank_viewed.php');

$cmid = optional_param('id', 0, PARAM_INT);
if (!$cmid) {
    $cmid = required_param('cmid', PARAM_INT);
}

$report = new mod_studentquiz_report($cmid);
require_login($report->get_course(), false, $report->get_coursemodule());

$params = array(
    'objectid' => $report->get_cm_id(),
    'context' => $report->get_context()
);
$event = \mod_studentquiz\event\studentquiz_report_rank_viewed::create($params);
$event->trigger();

$PAGE->set_title($report->get_ranking_title());
$PAGE->set_heading($report->get_heading());
$PAGE->set_context($report->get_context());
$PAGE->set_url($report->get_rank_url());

$output = $PAGE->get_renderer('mod_studentquiz', 'ranking');

echo $OUTPUT->header();

echo $output->view_rank($report);

echo $OUTPUT->footer();
